<?php

namespace Database\Seeders;

use Carbon\Carbon;
use App\Models\Student;
use Illuminate\Database\Seeder;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class StudentSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $student = [
            [
                'institute_id' => 1,
                'major' => 'sistem informatika',
                'ipk' => 3,
                'address' => 'jl.kebon sirih',
                'nik' => '318319290319990001',
                'phone' => '081234567890' ,
                'emergency_contact' => '081234567891',
                'division' => 'development application web base',
                'department' => 'PT.MNC',
                'job_role' => 'UI/UX',
                'start_date' => Carbon::now()->format('d-m-Y H:i:s'),
                'end_date' => Carbon::now()->addMonth('5')->format('d-m-Y H:i:s'),
                'status' => 'active',
                'supervisor_id' => 1,
            ],
            [
                'institute_id' => 1,
                'major' => 'teknik informatika',
                'ipk' => 3,
                'address' => 'jl.kebon sirih',
                'nik' => '318319290320000001',
                'phone' => '081234567890' ,
                'emergency_contact' => '081234567891',
                'division' => 'development application web base',
                'department' => 'PT.MNC',
                'job_role' => 'fullstack developer',
                'start_date' => Carbon::now()->format('d-m-Y H:i:s'),
                'end_date' => Carbon::now()->addMonth('2')->format('d-m-Y H:i:s'),
                'status' => 'inactive',
                'supervisor_id' => 1,
            ],
            [
                'institute_id' => 2,
                'major' => 'teknik informatika',
                'ipk' => 2.9,
                'address' => 'jl.kebon sirih',
                'nik' => '318319290320010001',
                'phone' => '081234567890' ,
                'emergency_contact' => '081234567891',
                'division' => 'development application web base',
                'department' => 'PT.MNC',
                'job_role' => 'fullstack developer',
                'start_date' => Carbon::now()->format('d-m-Y H:i:s'),
                'end_date' => Carbon::now()->addMonth('3')->format('d-m-Y H:i:s'),
                'status' => 'active',
                'supervisor_id' => 2,
            ],
            [
                'institute_id' => 2,
                'major' => 'teknik informatika',
                'ipk' => 3.6,
                'address' => 'jl.kebon sirih',
                'nik' => '318319290320020001',
                'phone' => '081234567890' ,
                'emergency_contact' => '081234567891',
                'division' => 'development application web base',
                'department' => 'PT.MNC',
                'job_role' => 'backend developer',
                'start_date' => Carbon::now()->format('d-m-Y H:i:s'),
                'end_date' => Carbon::now()->addMonth('3')->format('d-m-Y H:i:s'),
                'status' => 'active',
                'supervisor_id' => 2,
            ],
            [
                'institute_id' => 3,
                'major' => 'teknik informatika',
                'ipk' => 3.2,
                'address' => 'jl.kebon sirih',
                'nik' => '318319290320010001',
                'phone' => '081234567890' ,
                'emergency_contact' => '081234567891',
                'division' => 'development application web base',
                'department' => 'PT.MNC',
                'job_role' => 'frontend developer',
                'start_date' => Carbon::now()->format('d-m-Y H:i:s'),
                'end_date' => Carbon::now()->addMonth('1')->format('d-m-Y H:i:s'),
                'status' => 'active',
                'supervisor_id' => 3,
            ],
            [
                'institute_id' => 3,
                'major' => 'teknik informatika',
                'ipk' => 3.2,
                'address' => 'jl.kebon sirih',
                'nik' => '318319290320020034',
                'phone' => '081234567890' ,
                'emergency_contact' => '081234567894',
                'division' => 'development application web base',
                'department' => 'PT.MNC',
                'job_role' => 'frontend developer',
                'start_date' => Carbon::now()->format('d-m-Y H:i:s'),
                'end_date' => Carbon::now()->addMonth('1')->format('d-m-Y H:i:s'),
                'status' => 'active',
                'supervisor_id' => 3,
            ],
            [
                'institute_id' => 4,
                'major' => 'teknik informatika',
                'ipk' => 3.2,
                'address' => 'jl.kebon sirih',
                'nik' => '318319290320010012',
                'phone' => '081234567890' ,
                'emergency_contact' => '081234567895',
                'division' => 'development application web base',
                'department' => 'PT.MNC',
                'job_role' => 'backend developer',
                'start_date' => Carbon::now()->format('d-m-Y H:i:s'),
                'end_date' => Carbon::now()->addMonth('3')->format('d-m-Y H:i:s'),
                'status' => 'active',
                'supervisor_id' => 3,
            ],
            // [
            //     'institute_id' => 4,
            //     'major' => 'teknik informatika',
            //     'ipk' => 3.2,
            //     'address' => 'jl.kebon sirih',
            //     'nik' => '318319290320010012',
            //     'phone' => '081234567890' ,
            //     'emergency_contact' => '081234567895',
            //     'division' => 'development application web base',
            //     'department' => 'PT.MNC',
            //     'job_role' => 'backend developer',
            //     'start_date' => Carbon::now()->format('d-m-Y H:i:s'),
            //     'end_date' => Carbon::now()->addMonth('3')->format('d-m-Y H:i:s'),
            //     'status' => 'active',
            //     'supervisor_id' => 3,
            // ],
            // [
            //     'institute_id' => 4,
            //     'major' => 'teknik informatika',
            //     'ipk' => 3.2,
            //     'address' => 'jl.kebon sirih',
            //     'nik' => '318319290320010012',
            //     'phone' => '081234567890' ,
            //     'emergency_contact' => '081234567895',
            //     'division' => 'development application web base',
            //     'department' => 'PT.MNC',
            //     'job_role' => 'backend developer',
            //     'start_date' => Carbon::now()->format('d-m-Y H:i:s'),
            //     'end_date' => Carbon::now()->addMonth('3')->format('d-m-Y H:i:s'),
            //     'status' => 'active',
            //     'supervisor_id' => 3,
            // ],
            // [
            //     'institute_id' => 4,
            //     'major' => 'teknik informatika',
            //     'ipk' => 3.2,
            //     'address' => 'jl.kebon sirih',
            //     'nik' => '318319290320010012',
            //     'phone' => '081234567890' ,
            //     'emergency_contact' => '081234567895',
            //     'division' => 'development application web base',
            //     'department' => 'PT.MNC',
            //     'job_role' => 'backend developer',
            //     'start_date' => Carbon::now()->format('d-m-Y H:i:s'),
            //     'end_date' => Carbon::now()->addMonth('3')->format('d-m-Y H:i:s'),
            //     'status' => 'active',
            //     'supervisor_id' => 3,
            // ],
            // [
            //     'institute_id' => 4,
            //     'major' => 'teknik informatika',
            //     'ipk' => 3.2,
            //     'address' => 'jl.kebon sirih',
            //     'nik' => '318319290320010012',
            //     'phone' => '081234567890' ,
            //     'emergency_contact' => '081234567895',
            //     'division' => 'development application web base',
            //     'department' => 'PT.MNC',
            //     'job_role' => 'backend developer',
            //     'start_date' => Carbon::now()->format('d-m-Y H:i:s'),
            //     'end_date' => Carbon::now()->addMonth('3')->format('d-m-Y H:i:s'),
            //     'status' => 'active',
            //     'supervisor_id' => 3,
            // ],
            // [
            //     'institute_id' => 4,
            //     'major' => 'teknik informatika',
            //     'ipk' => 3.2,
            //     'address' => 'jl.kebon sirih',
            //     'nik' => '318319290320010012',
            //     'phone' => '081234567890' ,
            //     'emergency_contact' => '081234567895',
            //     'division' => 'development application web base',
            //     'department' => 'PT.MNC',
            //     'job_role' => 'backend developer',
            //     'start_date' => Carbon::now()->format('d-m-Y H:i:s'),
            //     'end_date' => Carbon::now()->addMonth('3')->format('d-m-Y H:i:s'),
            //     'status' => 'active',
            //     'supervisor_id' => 3,
            // ],
            // [
            //     'institute_id' => 4,
            //     'major' => 'teknik informatika',
            //     'ipk' => 3.2,
            //     'address' => 'jl.kebon sirih',
            //     'nik' => '318319290320010012',
            //     'phone' => '081234567890' ,
            //     'emergency_contact' => '081234567895',
            //     'division' => 'development application web base',
            //     'department' => 'PT.MNC',
            //     'job_role' => 'backend developer',
            //     'start_date' => Carbon::now()->format('d-m-Y H:i:s'),
            //     'end_date' => Carbon::now()->addMonth('3')->format('d-m-Y H:i:s'),
            //     'status' => 'active',
            //     'supervisor_id' => 3,
            // ],
            // [
            //     'institute_id' => 4,
            //     'major' => 'teknik informatika',
            //     'ipk' => 3.2,
            //     'address' => 'jl.kebon sirih',
            //     'nik' => '318319290320010012',
            //     'phone' => '081234567890' ,
            //     'emergency_contact' => '081234567895',
            //     'division' => 'development application web base',
            //     'department' => 'PT.MNC',
            //     'job_role' => 'backend developer',
            //     'start_date' => Carbon::now()->format('d-m-Y H:i:s'),
            //     'end_date' => Carbon::now()->addMonth('3')->format('d-m-Y H:i:s'),
            //     'status' => 'active',
            //     'supervisor_id' => 3,
            // ],
            // [
            //     'institute_id' => 4,
            //     'major' => 'teknik informatika',
            //     'ipk' => 3.2,
            //     'address' => 'jl.kebon sirih',
            //     'nik' => '318319290320010012',
            //     'phone' => '081234567890' ,
            //     'emergency_contact' => '081234567895',
            //     'division' => 'development application web base',
            //     'department' => 'PT.MNC',
            //     'job_role' => 'backend developer',
            //     'start_date' => Carbon::now()->format('d-m-Y H:i:s'),
            //     'end_date' => Carbon::now()->addMonth('3')->format('d-m-Y H:i:s'),
            //     'status' => 'active',
            //     'supervisor_id' => 3,
            // ],
            // [
            //     'institute_id' => 4,
            //     'major' => 'teknik informatika',
            //     'ipk' => 3.2,
            //     'address' => 'jl.kebon sirih',
            //     'nik' => '318319290320010012',
            //     'phone' => '081234567890' ,
            //     'emergency_contact' => '081234567895',
            //     'division' => 'development application web base',
            //     'department' => 'PT.MNC',
            //     'job_role' => 'backend developer',
            //     'start_date' => Carbon::now()->format('d-m-Y H:i:s'),
            //     'end_date' => Carbon::now()->addMonth('3')->format('d-m-Y H:i:s'),
            //     'status' => 'active',
            //     'supervisor_id' => 3,
            // ],
            // [
            //     'institute_id' => 4,
            //     'major' => 'teknik informatika',
            //     'ipk' => 3.2,
            //     'address' => 'jl.kebon sirih',
            //     'nik' => '318319290320010012',
            //     'phone' => '081234567890' ,
            //     'emergency_contact' => '081234567895',
            //     'division' => 'development application web base',
            //     'department' => 'PT.MNC',
            //     'job_role' => 'backend developer',
            //     'start_date' => Carbon::now()->format('d-m-Y H:i:s'),
            //     'end_date' => Carbon::now()->addMonth('3')->format('d-m-Y H:i:s'),
            //     'status' => 'active',
            //     'supervisor_id' => 3,
            // ],
        ];

        foreach ($student as $key => $value) {
            Student::create($value);
        }
    }
}
